In [1]:
import pandas as pd 
from datetime import datetime

## 1. 데이터 불러오기

In [55]:
# 클린 뷰티 등급을 구할 최종 전처리 데이터 Import 
data = pd.read_excel('../데이터/최종 데이터셋/최종 데이터셋_2022_11_22.xlsx')

## 2. 클린 뷰티 기준



1. 조건 
    1. 올리브영 선정 위험도 성분 개수 (올리브영 기준) (단위: 개) 
    2. 높은 위험도 성분 개수 (단위: 개)  
    3. 동물 실험을 하지 않는 브랜드 여부(단위: 1, 0) 
    4. 동물성 성분 개수(단위: 개) 
    5. 천연 유기농 성분 개수(단위: 개)  
    6. 공병 수거여부 (단위: 1, 0)
      

2. 등급 부여 기준(기본 : 시나리오 1)
    1. 모든 조건  충족: 1등급 = 클린 뷰티 

    2. 1~2개 조건 제외 모두 충족: 2등급  

    3. 3~4개 조건 제외 모두 충족: 3등급  

    4. 5~6개 조건 제외 모두 충족: 4등급

## 3. 클린 뷰티 등급 부여 함수 구현

In [54]:
# 조건 함수
def A(x):
    if x == 0:
        return 1
    else:
        return 0 
def B(x):
    if x == 0:
        return 1
    else:
        return 0 
def C(x):
    if x == 1:
        return 1
    else:
        return 0
def D(x):
    if x == 0:
        return 1
    else:
        return 0
def E(x):
    if x >= 1:
        return 1
    else:
        return 0
def F(x):
    if x == 1:
        return 1
    else:
        return 0

In [40]:
# 충족 여부 
def clean_beauty_y_or_n(data):

    data['A 조건 충족 여부'] = (data['올리브영 선정 유해 성분 개수'].apply(lambda x: A(x))) 
    data['B 조건 충족 여부'] = (data['높은 위험도 성분 개수'].apply(lambda x: B(x)))
    data['C 조건 충족 여부'] = (data['동물실험을 하지 않는 브랜드'].apply(lambda x: C(x))) 
    data['D 조건 충족 여부'] = (data['동물성 성분 개수'].apply(lambda x: D(x)))
    data['E 조건 충족 여부'] = (data['천연 및 유기농 성분 개수'].apply(lambda x: E(x))) 
    data['F 조건 충족 여부'] = (data['공병 수거를 하는 브랜드'].apply(lambda x: F(x)))
    
    return data

In [23]:
# 시나리오 1: 모든 조건이 충족되었을 경우 
def rating_1(x):
    if x == 6:
        return '1등급'
    elif x >= 4:
        return '2등급'
    elif x >= 2:
        return '3등급'
    else:
        return '4등급'   
def clean_beauty_grade_SNCN1(data):

    data['조건 충족 개수'] = (data['A 조건 충족 여부']) + (data['B 조건 충족 여부'])  + (data['C 조건 충족 여부']) + (data['D 조건 충족 여부']) + (data['E 조건 충족 여부']) + (data['F 조건 충족 여부'])
    
    data['클린 뷰티 등급'] = data['조건 충족 개수'].apply(lambda x : rating_1(x))    
    return data

In [31]:
# 시나리오 2: 브랜드 여부에 가산점을 주는 방식으로 

def rating_2(x):
    if x >= 6:
        return '1등급'
    elif x >= 4:
        return '2등급'
    elif x >= 2:
        return '3등급'
    else:
        return '4등급'


def clean_beauty_grade_SNCN2(data):

    data['조건 충족 개수'] = (data['A 조건 충족 여부']) + (data['B 조건 충족 여부']) + (data['C 조건 충족 여부']*2) + (data['D 조건 충족 여부']) + (data['E 조건 충족 여부']) + (data['F 조건 충족 여부'] *2)
    
    (data['C 조건 충족 여부']) + (data['F 조건 충족 여부'])
    
    data['클린 뷰티 등급'] = data['조건 충족 개수'].apply(lambda x : rating_2(x))    
    
    return data

In [41]:
# 시나리오 3: 비건을 위한 화장품 유해성분(올리브영, EWG) x, 동물성 성분 x일때, -> 등급이 아닌 인증 마크 
def rating_3(x):
    if x == 3:
        return 1
    else:
        return 0


def clean_beauty_grade_SNCN3(data):

    data['조건 충족 개수'] = (data['A 조건 충족 여부']) + (data['B 조건 충족 여부']) + (data['D 조건 충족 여부']) 
    
    data['비건 인증'] = data['조건 충족 개수'].apply(lambda x : rating_3(x))    
    
    return data

In [56]:
# 시나리오 4: 비건을 위한 화장품 유해성분(올리브영, EWG) x, 동물 실험 여부 x  -> 등급이 아닌 인증 마크 
def rating_4(x):
    if x == 3:
        return 1
    else:
        return 0


def clean_beauty_grade_SNCN4(data):

    data['조건 충족 개수'] = (data['A 조건 충족 여부']) + (data['B 조건 충족 여부']) + (data['C 조건 충족 여부']) 
    
    data['크루얼티프리 인증'] = data['조건 충족 개수'].apply(lambda x : rating_4(x))    
    
    return data

In [57]:
data = clean_beauty_y_or_n(data)
data = clean_beauty_grade_SNCN4(data)

In [64]:
# 현재 날짜 기준으로 저장
today_date = datetime.today().strftime("%Y_%m_%d") 

# 데이터를 원하는 형식으로 저장(csv일 경우 to_csv)
data.to_excel('../데이터/최종 데이터셋/클린뷰티_적용_최종 데이터셋_시나리오4_{}.xlsx'.format(today_date), index=False)

In [3]:
data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:2/cosmetic_project/데이터/최종 데이터셋/클린뷰티_적용_최종 데이터셋_시나리오1_2022_11_23.xlsx')

In [8]:
data.iloc[:, 31:]

,A 조건 충족 여부,B 조건 충족 여부,C 조건 충족 여부,D 조건 충족 여부,E 조건 충족 여부,F 조건 충족 여부,조건 충족 개수,클린 뷰티 등급
0,1,0,0,0,0,0,1,4등급
1,1,1,0,1,1,0,4,2등급
2,1,0,0,0,0,0,1,4등급
3,1,0,0,0,1,0,2,3등급
4,1,1,0,0,1,0,3,3등급
...,...,...,...,...,...,...,...,...
7302,1,0,0,0,1,0,2,3등급
7303,1,0,0,0,1,0,2,3등급
7304,1,0,0,1,1,0,3,3등급
7305,1,0,0,0,1,0,2,3등급
7306,1,0,0,0,0,0,1,4등급